# Install via CocoaPods pointing at current local codebase
use_frameworks!
pod 'RestKitSANetworking@MindSea/Network', :path => '../../'
pod 'RestKitSANetworking@MindSea/ObjectMapping', :path => '../../'
pod 'RestKitSANetworking@MindSea/CoreData', :path => '../../'
