platform :ios, '8.0'
use_frameworks!

# Install via CocoaPods pointing at current local codebase
pod 'RestKitSANetworking@MindSea/Network', :path => '../../'
pod 'RestKitSANetworking@MindSea/ObjectMapping', :path => '../../'
pod 'RestKitSANetworking@MindSea/Search', :path => '../../'
