platform :ios, '8.0'
use_frameworks!

link_with 'RKTwitterCoreData', 'Generate Seed Database'

# Install via CocoaPods pointing at current local codebase
pod 'RestKitSANetworking@MindSea/Network', :path => '../../'
pod 'RestKitSANetworking@MindSea/ObjectMapping', :path => '../../'
pod 'RestKitSANetworking@MindSea/CoreData', :path => '../../'
